### ISSUE TITLE
Calling forgetButton crashes app

### ISSUE THREAD

**Issue by Colemack** [hansemannn/ti.flic#3]
After calling Flic.getKnownButtons() it returns:

```
[INFO]  {
[INFO]      connectionState = 0;
[INFO]      identifier = "05A133DD-E854-3569-FCBA-5E36687DD804";
[INFO]      isReady = 1;
[INFO]      lowLatency = 0;
[INFO]      name = F022cfzC;
[INFO]      pressCount = 1414;
[INFO]      publicKey = bc4d3f91a343c6077e1f5eb3a7814d8d;
[INFO]      triggerBehavior = 0;
[INFO]      userAssignedName = "Siyou Green";
[INFO]  }
```

That's good! Thx for fixing that. It is also working, but when I call the forgetButton function, in my case:

`Flic.forgetButton('05A133DD-E854-3569-FCBA-5E36687DD804');`

 the app crashes immediately and without any logs.

**Comment by hansemannn** [comment]
Checking ... Are you running on main-thread or kroll-thread? I tested using main-thread:

```xml
<property name="run-on-main-thread" type="bool">true</property>
```

**Comment by Colemack** [comment]
Yes, main-thread = true

**Comment by hansemannn** [comment]
Fixed in https://github.com/hansemannn/ti.flic/releases/tag/1.0.2
